### ISSUE TITLE
How can it synchronize with github.com/gophercloud/gophercloud

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/nhncloud-sdk-go#25]
현재 nhncloud-sdk-go 저장소는 https://github.com/gophercloud/gophercloud 를 기반으로 개발된 것으로 소개되어 있습니다.
gophercloud의 소스가 갱신되는 사항에 대한 업데이트 방안이 어떻게 되는지 문의 드립니다.

**Comment by innodreamer** [comment]
@sykim-etri 이 저장소는 NHN Cloud 서비스 대사으로 개발을 위한 SDK이며, 
NHN Cloud API 문서와 실제 사용 테스트하면서 그 API 문서의 잘못된 점까지 보완해서 반영해가는 저장소입니다.
따라서, OpenStack용 SDK 이며 본래 저장소인 gophercloud가 업데이트되는 것과는 전혀 무관하게 유지되고 있습니다.

만약 NHN Cloud 서비스에 맞게 이 저장소 소스 코드가 업데이트가 필요하면 이 저장소 코드 기준으로 업데이트와 테스트를 마치신 뒤 PR로 올려주시면 됩니다.
