### ISSUE TITLE
What is the status of NHN K8S Service?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/nhncloud-sdk-go#26]
커밋 이력(https://github.com/cloud-barista/nhncloud-sdk-go/commit/edded742e9f25fe6a3cddb9541145e17a9eac2a1) 을 참고하니 NHN K8S Service에 대한 지원도 가능한 것으로 보입니다.
개발 현황이나 동작 시험 현황 등 상황이 어떻게 될까요?

**Comment by innodreamer** [comment]
@sykim-etri NHN Cloud용 PMKS 드라이버를 개발하실때 사용하시도록 제가 NHN K8S용 ClusterClient와 PMKS 드라이버 틀을 개발해서 지원해드렸습니다.
(참고) 위의 commit 과 https://github.com/cloud-barista/nhncloud/blob/main/nhncloud/resources/ClusterHandler.go

실제 PMKS 드라이버를 개발하실때 이 K8S용 client와 PMKS 드라이버 틀을 사용하셨지만, 그 외의 다른 기능들은 본 SDK를 업데이트해서 사용하시지는 않고 PMKS 드라이버 내에서 자체적으로 REST API를 처리하는 방식으로 개발하셨습니다.

상기 코드를 참고해보시면 아실 수 있습니다.

**Comment by innodreamer** [comment]
@sykim-etri NHN Clolud 드라이버 repo.에서의 위와 관련된 PR입니다.
https://github.com/cloud-barista/nhncloud/pull/87
https://github.com/cloud-barista/nhncloud/pull/89
