### ISSUE TITLE
Import gophercloud/openstack/networking/v2/networks package

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/nhncloud-sdk-go#32]
현재 nhncloud-sdk-go에는  gophercloud/openstack/networking/v2/networks가 없는 상황입니다.
CB-Spider의 ClusterHandler 개발시 해당 패키지의 기능이 필요한 상황입니다.
해당 패키지의 Import 관련한 의견 부탁드립니다.

https://github.com/gophercloud/gophercloud/tree/master/openstack/networking/v2/networks

@innodreamer

**Comment by sykim-etri** [comment]
@innodreamer 해당 패키지명이 vpc로 변경된 것을 확인하였습니다.

**Comment by innodreamer** [comment]
@innodreamer NHN Cloud에서 얼마전부터 지원하는 VPC/Subnet 제어 API에 따라 SDK를 변경한 상태입니다.
