### ISSUE TITLE
subnets package is different from vpcsubnets package

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/nhncloud-sdk-go#35]
NHN Cloud에서 vpcs 패키지를 추가하면서 기존 subnet 대신 vpcsubnet이라고 하는 새로운 패키지를 추가하여 API를 제공하는 것으로 판단됩니다. 따라서 subnets 패키지를 vpcsubnets로 이름을 변경하고 subnets 패키지를 추가해야 할 필요가 있습니다.

* subnets
  * https://docs.nhncloud.com/ko/Network/VPC/ko/public-api-compat/#_2

* vpcsubnets
  * https://docs.nhncloud.com/ko/Network/VPC/ko/public-api/#vpc_7

이에 따라 CB-SP용 NHN 드라이버도 변경이 필요할 것으로 보입니다.
@innodreamer

**Comment by innodreamer** [comment]
@sykim-etri 
vpcsubnet은 정보 객체의 이름이면서 subnet 제어 URL에 적용된 이름입니다.

VPC/Subnet 관련 신규 API의 vpcsubnet 객체 관련 사항은 얼마전 신규 API를 적용하여 보완 개발할때 이미 nhncloud SDK와 nhncloud driver에 반영되어 있습니다.

https://github.com/cloud-barista/nhncloud-sdk-go/blob/b0c008fddaf55d62164336b981eeaed30e1afafd/openstack/networking/v2/subnets/requests.go#L100
https://github.com/cloud-barista/nhncloud-sdk-go/blob/b0c008fddaf55d62164336b981eeaed30e1afafd/openstack/networking/v2/subnets/results.go#L128
https://github.com/cloud-barista/nhncloud-sdk-go/blob/b0c008fddaf55d62164336b981eeaed30e1afafd/openstack/networking/v2/subnets/urls.go#L16

**Comment by sykim-etri** [comment]
@innodreamer 
앞서 안내드린 링크와 같이 NHN Cloud에서 subnets와 vpcsubnets를 둘다 제공하고 있기 때문에 현재의 subnets를 vpcsubnets로 이름 변경하고, subnets 패키지를 신규로 포함해야 하는 상황입니다.
대략적으로 개발된 소소코드가 있어서 조만간 PR을 진행할 예정이오니 검토해 주시면 되겠습니다.

더불어 상기 PR을 반영하는 경우 CB-SP의 NHN 드라이버에도 변경이 필요하기 때문에 해당 변경 내용도 PR을 진행할 예정입니다.

**Comment by innodreamer** [comment]
@sykim-etri 네. PR 올려주시면 검토 후 merge하고, 드라이버에도 변경 사항을 반영하겠습니다.
